
dataset: celeba
dim: [3, 64, 64]
task_ids: [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 
    10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 
    20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 
    30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
]
objectives: [
    BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, 
    BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, 
    BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, 
    BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, 
    BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, 
    BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, 
    BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, 
    BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, 
    BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, 
    BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss, BinaryCrossEntropyLoss,
]

reference_point: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
n_partitions: 2
epochs: 100
batch_size: 32
eval_every: 5
checkpointing: True



# lower fidelities:
# 
# task_ids=[16, 22],                                    # easy tasks
# task_ids=[25, 27],                                    # hard tasks
# task_ids=[16, 22, 24],                                # 3 objectives
# task_ids=[16, 22, 24, 26],                            # 4 objectives
# task_ids=[random.randint(0, 39) for _ in range(10)],  # 10 random tasks
