
dataset: celeba
dim: [3, 64, 64]

accuracy_class: 2       # attractive
sensible_attribute: 20  # male

objectives: [BinaryCrossEntropyLoss, ddp]

reference_point: [1, 1]

n_partitions: 25

epochs: 10
batch_size: 32
eval_every: 5
checkpointing: False



# lower fidelities:
# 
# task_ids=[16, 22],                                    # easy tasks
# task_ids=[25, 27],                                    # hard tasks
# task_ids=[16, 22, 24],                                # 3 objectives
# task_ids=[16, 22, 24, 26],                            # 4 objectives
# task_ids=[random.randint(0, 39) for _ in range(10)],  # 10 random tasks
