_BASE_: _base.yaml

# task_ids: [
#     0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 
#     10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 
#     20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 
#     30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
# ]

epochs: 100
eval_every: 20

method: cosmos

dampening: 0. #000001
lambda_clipping: 1.
lambda_lr: 3.   # .2 * 8 gpus
n_train_rays_cosmos: 2
train_ray_mildening: 0.6
upsample_ratio: 1.

lr_scheduler: CosineAnnealing
lr: 0.0001
weight_decay: 0.

  
