
dataset: adult
dim: [88]
objectives: [
  BinaryCrossEntropyLoss,
  ddp]

# accuracy_class: 2       # attractive
sensible_attribute: "gender"

epochs: 50
eval_every: 2

loss_mins: [0.25, 0.0]
loss_maxs: [1, .1]