
dataset: adult
dim: [88]
objectives: [
  BinaryCrossEntropyLoss,
  ddp]
epochs: 50
eval_every: 2

# results of hpo, dont change!
cosmos:
  lr: 0.0001
  loss_mins: [0.25, 0.0]
  loss_maxs: [1, .1]
  clipping: 10.



mgda:
  normalization_type: 'loss'

# phn: defaults

# pmtl: defaults

# single_task: defaults. Please provide a task id when running the experiment