
dataset: adult
dim: [88]
objectives: [
  BinaryCrossEntropyLoss,
  ddp]
epochs: 50
eval_every: 1

# results of hpo
cosmos:
  lamda: 0.
  alpha: [1., 1.]    # concentration parameter behaves differently
  normalize: True
  lr: 0.0001
  instances: False

mgda:
  normalization_type: 'loss'

# phn: defaults

# pmtl: defaults

# single_task: defaults. Please provide a task id when running the experiment