
dataset: compass
dim: [20]
objectives: [BinaryCrossEntropyLoss, ddp]
epochs: 50
eval_every: 5

# results of hpo
cosmos:
  lr: 0.005
  loss_mins: [0.2, 0.0]
  loss_maxs: [1, .1]
  clipping: 50.



mgda:
  normalization_type: 'loss'


# phn: defaults

# pmtl: defaults

# single_task: defaults. Please provide a task id when running the experiment