
dataset: credit
dim: [90]
objectives: [BinaryCrossEntropyLoss, ddp]
epochs: 50
eval_every: 2
batch_size: 56

cosmos:
  lr: 0.0005
  loss_mins: [0.4, 0.0]
  loss_maxs: [1, .1]
  clipping: 10.
  lambda_lr: 0.2

mgda:
  normalization_type: 'loss'


# phn: defaults

# pmtl: defaults

# single_task: defaults. Please provide a task id when running the experiment
