
dataset: multi_mnist
dim: [1, 36, 36]
task_ids: [l, r]    # top left, bottom right
objectives: [CrossEntropyLoss, CrossEntropyLoss]
epochs: 100
eval_every: 2

# results of hpo
cosmos:
  lamda: 3.7724
  alpha: [0.3089, 1.0183]
  lr_scheduler: MultiStep
  lr: 0.000491
  normalize: false
  instances: false


mgda:
  normalization_type: 'loss'
  lr_scheduler: MultiStep

phn:
  lr_scheduler: MultiStep 

pmtl:
  lr_scheduler: MultiStep 

single_task:
  lr_scheduler: MultiStep 

