
dataset: multi_mnist
dim: [1, 36, 36]
task_ids: [l, r]    # top left, bottom right
objectives: [CrossEntropyLoss, CrossEntropyLoss]
epochs: 100
eval_every: 2

# results of hpo
cosmos:
  lamda: .2
  alpha: [1.]
  lr_scheduler: MultiStep
  lr: 1e-3

mgda:
  normalization_type: 'loss'
  lr_scheduler: MultiStep

phn:
  lr_scheduler: MultiStep 

pmtl:
  lr_scheduler: MultiStep 

single_task:
  lr_scheduler: MultiStep 

