_BASE_: _base.yaml

method: cosmos

train_eval_every: 0
eval_every: 0

loss_mins: [270.0, 190.0]
loss_maxs: [300.0, 220.0]

epochs: 100
batch_size: 256

train_ray_mildening: 0.5
dampening: 0.0
lambda_clipping: 1500.
lambda_lr: 20.

lr_scheduler: CosineAnnealing
lr: 0.001
weight_decay: 0.0

vae_params:
  dropout: 0.0
  no_latent_features: 800
  dec1_in: 800
  enc2_out: 1600
  norm_std: 0.01