_BASE_: _base.yaml

method: cosmos

dim: [5, 64, 64]
alpha: 0.2
lamda: 1.

lr_scheduler: CosineAnnealing
weight_decay: 0.0075

lr: 0.0005
batch_size: 128

checkpointing: True
eval_every: 5
test_eval_every: 5